version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout:
      - node:
          steps:
            - run: sudo apt-get install tree -y
            - run: tree . -l 2
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test