version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get install tree -y
            - run: pwd
            - run: tree . -l 4
            - run: cd onlineboardgamesui && npm install
            - run: cd onlineboardgamesui && npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test