version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout:
      - node:
          steps:
            - run: pwd
            - run: ls -al
            - run: cd onlineboardgamesui 
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test:
          working_directory: ~/onlineboardgames